### ISSUE TITLE
[Redmi Note 8 Pro] Multiple bugs

### ISSUE THREAD

**Issue by tvardero** [phhusson/treble_experimentations#1028]
*Please read **this thread** or **[device wiki](https://github.com/phhusson/treble_experimentations/wiki/Xiaomi-Redmi-Note-8-Pro)** first before creating new issues.*

Redmi Note 8 Pro 128 Gb [begonia]
AOSP 10 latest ARM64 AB, gappsed version.
Magisk 20.1
Mediatek Helio G90T
MIUI 11 vendor global (can't be downgraded!) 

- [ ]  RIL is broken (Moved to issue #1051) [AOSP 9 only]
- [ ]  In offline charging, phone boots into recovery after plug-in. [both AOSP 10 and 9]
- [ ]  Broken night light (flickering with orange colour). [both AOSP 10 and 9]
- [ ]  12bit minimum brightness (Issue #224) [both AOSP 10 and 9]
- [ ] Glitchy camera despite using Camera2API or not. (Moved to issue #1154 ) [AOSP 10]
- [x]  Broken audio recorder, also no media working (music/video, stuck on 0:00). But, external speaker IS working, coz phone numpad emits sounds using it. Plus youtube.com on WebView browser works perfectly. (please, update your vender to Q) [AOSP 10 only]
- [x]  Glitchy system animations (animation speed broken?). [AOSP 10 only]
- [x]  No autobrightness (Moved to #1040) (Overlay was [made](https://github.com/phhusson/vendor_hardware_overlay/pull/174).)
- [x] Rounded corners detection (Overlay was [made](https://github.com/phhusson/vendor_hardware_overlay/pull/174).)
- [x]  Flickering brightness (Fixed in issue #1019 ). [both AOSP 10 and 9]

Can provide any log you ask

**Comment by phhusson** [comment]
Got a video?

**Comment by tvardero** [comment]
Will make one this night (Kiev time)

**Comment by tvardero** [comment]
Ignore the audio ☺️
https://drive.google.com/file/d/11FAs9y9yAxUAv2fDAP1KH5EXI7N_zevw/view?usp=drivesdk

**Comment by tvardero** [comment]
any further instructions?

**Comment by n19htmare** [comment]
Any thoughts on the glitchy graphics? Seems to be quite common.

**Comment by phhusson** [comment]
Ok thanks for the video. 
So from what I can tell, your glitchy animations is just the embedded videos not rendering correctly which is a known issue. 
The broken night light issue is very interesting because probably related to the previous one, thanks for bringing that up. 

For auto-brightness you'll probably just need to make an overlay. Create a new issue with stock ROM framework res and getprop and /vendor/build.prop

**Comment by tvardero** [comment]
> For auto-brightness you'll probably just need to make an overlay. Create a new issue with stock ROM framework res and getprop and /vendor/build.prop
Done.

Got some logcats (finally i did it) with audio recorder failure, also with mp3 playback failure (playing mp3 from file system):
[logcat_playingmp3file.txt](https://github.com/phhusson/treble_experimentations/files/4016215/logcat_playingmp3audio.txt)
[logcat_audiorecorder.txt](https://github.com/phhusson/treble_experimentations/files/4016216/logcat_usingrecorder.txt)

**Comment by proganime1200** [comment]
your using a latest miui 11 am i correct thats probably the fault of the vendor why not downgrade to much older one like miui 10 vendor

**Comment by tvardero** [comment]
> your using a latest miui 11 am i correct thats probably the fault of the vendor why not downgrade to much older one like miui 10 vendor

Not possible, anti-rollback protection.

**Comment by mmtrt** [comment]
> Not possible, xiaomi anti-rollback protection.

Phone does not have arb protection, I usually do downgrades back forth without any issue.

**OT:** how you boot this GSI? is there any step needed beside flashing system, I'm always getting redmi logo bootloop no matter what I tried **i.e** close avb, .eu rom, lrtwrp.

**Comment by tvardero** [comment]
> > Not possible, xiaomi anti-rollback protection.
> 
> Phone does not have arb protection, I usually do downgrades back forth without any issue with fastboot rom flash through miflash tool.
> 
> **OT:** how you boot this GSI? is there any step needed beside flashing system, I'm always getting redmi logo bootloop no matter what I tried **i.e** close avb, .eu rom, lrtwrp.

Flash stock.
Get twrp.
Make a backup of system and data.
Format data -> yes.
Flash GSI. Android 9 GSIs have major RIL issue, android 10 GSIs have major audio issue.
To flash another GSI or revert to stock you use your backup of system partition.

NEVER EVER RESTORE ANYTHING ELSE THAN SYSTEM OR DATA, bootloop imminent.

Note: you can flash any GSI you want, but you will never flash GApps through recovery (it needs more space in system partition), else you will get bootloop (by resizing system partition).

**Comment by Hopefullyidontgetbanned** [comment]
Can confirm media is broken on every app except web browser - (aosp 10)
On YouTube, the first frame of a video loads then proceeds to crash.
On Twitter, first frame loads but stays at 0:00, seeking causes it crash.
YouTube log:  
[logcat_01-07-2020_22-09-49.txt](https://github.com/phhusson/treble_experimentations/files/4033796/logcat_01-07-2020_22-09-49.txt)
Twitter Video playback Log: 
[logcat_01-07-2020_22-14-11.txt](https://github.com/phhusson/treble_experimentations/files/4033802/logcat_01-07-2020_22-14-11.txt)

**Comment by Hopefullyidontgetbanned** [comment]
Can confirm media is broken on every app except web browser - (aosp 10)
On YouTube, the first frame of a video loads then proceeds to crash.
On Twitter, first frame loads but stays at 0:00, seeking causes it crash.
YouTube log:  
[logcat_01-07-2020_22-09-49.txt](https://github.com/phhusson/treble_experimentations/files/4033796/logcat_01-07-2020_22-09-49.txt)
Twitter Video playback Log: 
[logcat_01-07-2020_22-14-11.txt](https://github.com/phhusson/treble_experimentations/files/4033802/logcat_01-07-2020_22-14-11.txt)

**Comment by Hopefullyidontgetbanned** [comment]
Can confirm calling works, however multimedia playback on most Android apps are broken. So nothing about the hardware seems off

**Comment by jumper047** [comment]
Workaround for night light - toggle on "Disable HW overlays" in developer options.

**Comment by jumper047** [comment]
@tvardero actually you can roll back via fastboot without issues. But on MIUI 10 vendor sound issue remains

**Comment by jumper047** [comment]
Someone on RN8Pro telegram group reported that ``` setprop debug.stagefright.omx_default_rank.sw-audio 1 &    setprop debug.stagefright.omx_default_rank 0``` fixes sound issue. I think if  issue  https://github.com/phhusson/treble_experimentations/issues/1122 will be implemented it must be mentioned on device's wiki page

**Comment by tvardero** [comment]
phh's AOSP 10 v212 gappsed tested, MIUI 11 vendor (android 9). What works and not works, out of box:
+ No more glitched 2D embedded animations (little laggy, but not glitchy).
+ Brightness and autobrightness fixed (no "A" button, but you can turn it in settings)
+ Macro and ultrawide cams works in google camera port ([telegram](https://t.me/rn8pro_gcam))
+ IR blaster fine
- No 64MP, only 16MP on main cam in google camera port
- Nightlight still broken
- Still no media (audio/video) working outside of WebView browser.

**Comment by phhusson** [comment]
" Go developer settings -> Toggle on "Disable HV overlays" ("Отключить аппаратные наложения")" 

sadly this will lower global performance, and increase battery consumption

> No 64MP, only 16MP on main cam in google camera port

You can access 64MP in stock rom?

**Comment by tvardero** [comment]
>" Go developer settings -> Toggle on "Disable HV overlays"
Nah, i'm too lazy do it each reboot, so i'll prefer to wait for a fix.

> You can access 64MP in stock rom?
Yes, i can.

Btw, how to uninstall SU? Can't get rid of it (unSU script, magisk installer, twrp->unroot, none of them removed this root on gappsed version). Might be that is the reason why basic integrity fails. 
On the second hand i can't use vanilla aosp, because i can't install gapps. The reason is insufficient space in system partition, but resizing of partition leads to bootloop.   :'(

**Comment by jumper047** [comment]
@tvardero i seeing somewhere on xda recipe how to disable hw overlays permanently, but don't tested it due to reasons mentioned by @phhusson . About root - there must be a special script for removing it,
/system/bin/phh-securize.sh
Run it as root.

**Comment by tvardero** [comment]
> /system/bin/phh-securize.sh

Make device bootloop.

**Comment by jumper047** [comment]
Also faced bootloop on quack without gapps. Was able to boot after deleting /system/phh/secure file.
About notch - strange, in my case notch detected correctly. Can you provide screenshot?

**Comment by tvardero** [comment]
>Also faced bootloop on quack without gapps. Was able to boot after deleting /system/phh/secure file.
>About notch - strange, in my case notch detected correctly. Can you provide screenshot?

Was wrong about that, sorry.

**Comment by jumper047** [comment]
There is no sound issue with latest Q based vendor (tested on Andy's LineageOS 17).

**Comment by tvardero** [comment]
Closing because totally outdated.

For new bugs better to open new issue.
